# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

comment:
  layout: "flags, files"
  behavior: default
  require_changes: true
  require_base: true
  branches:            
    - "main"
    - "develop"

coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: "0.5%"
    patch:
      default:
        informational: true
        target: auto
        threshold: "0.5%"

github_checks:
    annotations: false